<Project>
  <PropertyGroup>
    <Authors>Denis Cuciuc</Authors>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageProjectUrl>https://github.com/deniscuciuc/dotnet-$([System.String]::Copy('$(MSBuildProjectName)').Replace('DenisCuciuc.', '').ToLowerInvariant())</PackageProjectUrl>
    <RepositoryUrl>$(PackageProjectUrl)</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <CopyrightYear Condition="'$(CopyrightYear)' == ''">2026</CopyrightYear>
    <Copyright>© $(CopyrightYear) Denis Cuciuc</Copyright>
  </PropertyGroup>
</Project>