<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    </PropertyGroup>

    <ItemGroup Label="Microsoft.Extensions">
        <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.5" />
        <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.5" />
        <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
        <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
        <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.5" />
        <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.5" />
        <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.5" />
        <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.5" />
    </ItemGroup>

    <ItemGroup Label="Third-party">
        <PackageVersion Include="System.IO.Hashing" Version="10.0.12" />
    </ItemGroup>

    <ItemGroup Label="Build">
        <PackageVersion Include="MinVer" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup Label="Benchmarks">
        <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    </ItemGroup>

    <ItemGroup Label="Testing">
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
        <PackageVersion Include="NSubstitute" Version="6.2.0" />
        <PackageVersion Include="xunit" Version="2.9.3" />
        <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
        <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    </ItemGroup>
</Project>
